eventapis:
  storeConfig:
    contactPoints: localhost:9042
    keyspaceName: test
  eventRecords:
    order: orderevents
  eventBus:
    bootstrapServers: localhost:9092
    consumer:
      groupId: ${info.build.artifact}

payment:
  url: http://localhost:8062
  process-path: /payments/v1/create

stock:
  url: http://localhost:8064
  process-path: /stocks/v1/item-sold

server:
  port: 8160

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: USR_ORDER
    password: qwe123
    platform: ORACLE
    tomcat:
      validation-query-timeout: 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      initial-size: 2
      min-idle: 1
      max-idle: 4
      max-active: 8
      max-wait: 3000
      min-evictable-idle-time-millis: 60000
      log-abondoned: true
      log-validation-errors: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    com.datastax.driver.core.QueryLogger.NORMAL: DEBUG
    com.datastax.driver.core.QueryLogger.ERROR: DEBUG
